name="ExampleLog"
path="/path/example.log"

[[monitors]]
name="monitorOne"
match="one"
interval=1
expression="1<%d"
webhook="https://oapi.dingtalk.com/robot/send?access_token=xxx"
comment="commentOne"

[[monitors]]
name="monitorTwo"
match="two"
interval=5
expression="20<%d"
webhook="https://oapi.dingtalk.com/robot/send?access_token=xxx"
comment="commentTwo"